baseurl   : https://www.indeed.com/jobs?
baselimit : "&limit=50"
maxresults : 200

jobs:
- job:
  keyword: web developer
  location:
    - Austin Tx
    - Remote

- job:
  keyword: full stack developer
  location:
    - Remote
    - Canada
